### ISSUE TITLE
Bunch of quick fixes

### ISSUE THREAD

**Issue by svenwiltink** [DAKYSKYE/PISD#1]
- If you make your config.json match the structs you use for storing the data you can get rid of all the code here: https://github.com/DAKYSKYE/PISD/blob/master/main.go#L141. That way you don't need type assertion either in the rest of your code. Strict typing is what makes go great, use it to your advantage.
- Get rid of the isErr function. It doesn't increase readability or functionality
- You are storing the token as plain text, which is bad considering it is basically a password. You want to look into hashing it.

**Comment by DAKYSKYE** [comment]
This is my feedback on your issue:
* gonna remove "groups* i.e mysql, connection, cmds etc. from json, they're arrays but I only use the only first index.
* I may keep it, I like to get error printed and act if error is caught. So I mean, by this function I println error and then act. isErr returns true if it's error, so this is the example why I like it:
```go
if isErr(<err>, <error message>) {
    os.Exit(3)
}
```
That's better way for me to handle errors instead of checking err, then wrapping it etc. every time
* That must be done so soon

**Comment by 0xFA7E** [comment]
Why hash the token? Not going to be able to use the hash on startup, so the user would have to wind up plugging the token back in. 

The config file should just be treated as sensitive info in the first place, if someone grabs it you already had issues to begin with.

**Comment by svenwiltink** [comment]
With the token I meant the verification code. The code only needs to be handed out once and there is no need to store the original. Instead you can save the salted hash and use that to verify that the correct one has been entered.

**Comment by svenwiltink** [comment]
After an intensive discussion @DAKYSKYE came to the conclusion hashing the verification tokens isn't needed because "His bot can't be hacked and the tokens are of no use". The overall consensus was that he should, but the advice was ignored.

**Comment by DAKYSKYE** [comment]
@svenwiltink I've said that there was no way to get user's database hacked by my bot's way. There is no chance of that until hacker hacks whole user VPS and take a look into config.json configured for my bot. My bot leaks nothing, until viewing ***config.json*** for the whole information.

**Comment by DAKYSKYE** [comment]
But some time ago I also said I will give user a choice: does he/she want to hash verification code ? then I will start adding hash methods on updates, the first one will be bcyrpt.

**Comment by 0xFA7E** [comment]
Very very dangerous assumption that the bot itself can't be hacked. It's fundamentally proven that you can't prove something to be unhackable, you can only practice defense in depth to make things so hard that you raise the bar higher than what threats you have to worry about are willing to commit to. 

And yes, a compromise from something other than the bot itself IS something you should consider and safeguard against as much as possible. Some things simply are not going to be feasible to protect like the bot token, but that's what's called "acceptable risk". Passwords and tokens received by users on the other hand that have no business sticking around in the clear shouldn't. You want to minimize your liability to your users in the event of a compromise as much as you realistically can.

**Comment by 0xFA7E** [comment]
Also as for the whole can't be hacked bit. I see one potential vulnerability. You build.your SQL queries based off info from the config page. If someone managed to get write access to the configuration they could inject SQL commands to leak the DB. 

Granted if they have write access to the config they can likely just steak the other valuable information, but this would be relevant in an instance where an attacker has the ability to access the configuration page but not the underlying MySQL database directly (say because of iptables configuration). 

It's a pretty low impact and low risk vulnerability that many projects have and deem acceptable risk, but strictly speaking it's still a vulnerability which disproves your claim that the bot itself cannot be hacked.

**Comment by svenwiltink** [comment]
Apart from that the discord handle is not immutable and can be stolen by a different user if the original user changed name. Instead the immutable User.ID should be used as a key.

**Comment by DAKYSKYE** [comment]
Got fixed in [v0.1-alpha release](https://github.com/DAKYSKYE/PISD/releases/tag/v0.1-alpha)
